[package]
name = "flamegraphs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-audio-api = { path = "../" }
rand = "0.8"

[profile.release]
debug = true
