# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

# Same name as the file for consistent identification
name: pre-commit

# read-only repo token, no access to secrets
permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  pre-commit:
    name: Detecting code style issues
    runs-on: ubuntu-latest
    steps:
      - name: Install ALSA and Jack dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libasound2-dev libjack-jackd2-dev

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Generate Cargo.lock
        run: cargo generate-lockfile

      - name: Cache Rust toolchain and build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          # The cache should not be shared between different workflows and jobs.
          shared-key: ${{ github.workflow }}-${{ github.job }}

      - name: Detect code style issues (push)
        uses: pre-commit/action@v3.0.0
        if: github.event_name == 'push'

      - name: Detect code style issues (pull_request)
        uses: pre-commit/action@v3.0.0
        if: github.event_name == 'pull_request'
        env:
          SKIP: no-commit-to-branch
